"""How often the barrier gain's guard binds, and how far the gain actually runs."""
import os
import argparse
import warnings

warnings.filterwarnings("ignore")
import numpy as np

import compare as C
import plant as P
import mc_robustness as M

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "paper_AST", "barrier_numbers.tex")


def probe(seed, eps):
    rng = np.random.RandomState(1_000_000 + seed)
    b = rng.normal(0, 0.12)
    model = C.BiasedModel(C.Sur, b)
    sensor = rng.uniform(0.002, 0.006)
    P.RATE = M._RATE0 * rng.uniform(0.7, 1.3)
    P.SIGMA = M._SIGMA0 * rng.uniform(0.7, 1.4)
    g = P.VonKarmanGust(rng, amp=rng.uniform(0.03, 0.07))
    g.w = 2 * np.pi * np.exp(rng.uniform(np.log(0.2), np.log(1.5), len(g.w)))
    try:
        L = C.run_bfasta(model, gust=g, sensor=sensor, seed=seed, eps=eps)
    finally:
        P.RATE = M._RATE0.copy()
        P.SIGMA = M._SIGMA0
    s = L["viol"]
    binds = int(np.sum((s >= 0.999 * eps) & (s < eps)))
    return dict(steps=len(s), binds=binds, kmax=float(L["K"].max()),
                smax=float(s.max()))


def main(n):
    eps = M.EPS
    r = [probe(k, eps) for k in range(n)]
    steps = sum(x["steps"] for x in r)
    binds = sum(x["binds"] for x in r)
    kmax = max(x["kmax"] for x in r)
    smax = max(x["smax"] for x in r)
    kcap = eps * (0.999 * eps) / (eps - 0.999 * eps) + 0.5

    V = dict(bcTrials=n, bcSteps=steps, bcBinds=binds,
             bcBindsPct=f"{100*binds/steps:.4f}",
             bcKmax=f"{kmax:.1f}", bcKcap=f"{kcap:.1f}",
             bcKheadroom=f"{kcap/kmax:.1f}",
             bcSmax=f"{smax:.4f}", bcEps=f"{eps:g}")
    lines = ["% barrier_numbers.tex -- generated by barrier_clip.py. Do not edit.", ""]
    lines += ["\\newcommand{\\%s}{%s}" % (k, v) for k, v in V.items()]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w").write("\n".join(lines) + "\n")

    print(f"{n} trials, {steps} steps, epsilon = {eps}")
    print(f"  guard binds on {binds} steps ({100*binds/steps:.4f} %)")
    print(f"  gain reaches {kmax:.1f} against a guard ceiling of {kcap:.1f} "
          f"-- a factor {kcap/kmax:.1f} of headroom")
    print(f"  peak |s| {smax:.4f} against the band {eps}")
    print(f"\nwrote {OUT}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=200)
    main(ap.parse_args().n)
