"""How much of the available descent each operating point actually realises."""
import os
import warnings

warnings.filterwarnings("ignore")
import numpy as np

from writeonce import write_if_changed, frame_if_changed
import pandas as pd

import control3 as C3
import plant as P

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_CSV = os.path.join(HERE, "descent_fraction.csv")
OUT_TEX = os.path.join(HERE, "paper_AST", "descent_numbers.tex")
BUDGET = 0.05

LABEL = {"SG-FTSMC": "Ft", "BF-STA": "Bf", "CLF-QP": "Qp", "MPC": "Mp"}
LABEL_NAME = {k: k for k in LABEL}


def _eps():
    src = open(os.path.join(HERE, "mc_robustness.py")).read()
    for line in src.splitlines():
        if line.startswith("EPS = "):
            return float(line.split("=")[1].split("#")[0])
    raise RuntimeError("EPS not found in mc_robustness.py")


def main():
    cc = pd.read_csv(os.path.join(HERE, "controller_comparison.csv"))
    nom = cc[cc.condition == "nominal"]

    rows = []
    for (U, CLreq), grp in nom.groupby(["U", "CLreq"], sort=True):
        import compare as C
        C.set_operating_point(U, CLreq)
        loud = C.LOUD.copy()
        loud_spl = C.loud_level(U)
        us = C.setpoint(C.Sur, budget=BUDGET)
        quiet_spl = float(P.tSPL.predict([[us[0], us[1], us[2], U]])[0])
        assert abs(loud_spl - float(grp.loud_SPL.iloc[0])) < 1e-6, (
            f"loud reference disagrees at ({U}, {CLreq}): "
            f"{loud_spl} here, {grp.loud_SPL.iloc[0]} in controller_comparison.csv")
        avail = loud_spl - quiet_spl
        for _, r in grp.iterrows():
            rows.append(dict(U=U, CLreq=CLreq, controller=r.controller,
                             loud_SPL=loud_spl, quietest_feasible_SPL=quiet_spl,
                             quietest_config="%.2f/%.2f/%.2f" % tuple(us),
                             available_descent_dB=avail,
                             realised_dB=float(r.reduction),
                             fraction_realised_pct=100 * float(r.reduction) / avail))
    d = pd.DataFrame(rows)
    frame_if_changed(OUT_CSV, d, index=False)

    per_pt = d.groupby(["U", "CLreq"]).fraction_realised_pct
    lo, hi, mean = per_pt.min(), per_pt.max(), per_pt.mean()
    pts = list(mean.index)

    eps = _eps()
    V = {
        "dfEps": f"{eps:g}",
        "dfRmsMax": f"{cc.lift_RMS.max():.3f}",
        "dfRmsFactor": f"{eps / cc.lift_RMS.max():.1f}",
    }
    per = cc.groupby("controller").lift_RMS
    for name, tag in LABEL.items():
        if name in per.groups:
            V["dfRms" + tag + "Lo"] = f"{per.min()[name]:.3f}"
            V["dfRms" + tag + "Hi"] = f"{per.max()[name]:.3f}"

    if "lift_max" in cc.columns:
        pmx = cc.groupby("controller").lift_max
        V["dfMaxMax"] = f"{cc.lift_max.max():.3f}"
        V["dfMaxFactor"] = f"{eps / cc.lift_max.max():.1f}"
        V["dfMaxWorst"] = LABEL_NAME.get(
            cc.loc[cc.lift_max.idxmax(), "controller"],
            str(cc.loc[cc.lift_max.idxmax(), "controller"]))
        for name, tag in LABEL.items():
            if name in pmx.groups:
                V["dfMax" + tag + "Lo"] = f"{pmx.min()[name]:.3f}"
                V["dfMax" + tag + "Hi"] = f"{pmx.max()[name]:.3f}"
        V["dfWholeMax"] = f"{cc.whole_max.max():.3f}"
    for k, (U, CL) in enumerate(pts):
        tag = "dfPt" + "ABC"[k] if k < 3 else f"dfPt{k}"
        V[tag + "U"] = f"{U:.0f}"
        V[tag + "CL"] = f"{CL:.2f}"
        V[tag + "Avail"] = f"{d[(d.U == U) & (d.CLreq == CL)].available_descent_dB.iloc[0]:.2f}"
        V[tag + "Pct"] = f"{mean[(U, CL)]:.0f}"
        V[tag + "Spread"] = f"{hi[(U, CL)] - lo[(U, CL)]:.1f}"
    V["dfSpreadMax"] = f"{float((hi - lo).max()):.1f}"
    V["dfAxisFloor"] = f"{float(np.floor(lo.min() / 5.0) * 5.0 - 5.0):.0f}"
    db = d.groupby(["U", "CLreq"]).realised_dB
    V["dfSpreadMaxDb"] = f"{float((db.max() - db.min()).max()):.2f}"

    lines = ["% descent_numbers.tex -- generated by descent_fraction.py.",
             "% Do not edit by hand.", ""]
    lines += ["\\newcommand{\\%s}{%s}" % (k, v) for k, v in V.items()]
    write_if_changed(OUT_TEX, "\n".join(lines) + "\n")

    print(d.groupby(["U", "CLreq"]).agg(
        available=("available_descent_dB", "first"),
        realised_lo=("realised_dB", "min"),
        realised_hi=("realised_dB", "max"),
        pct_lo=("fraction_realised_pct", "min"),
        pct_hi=("fraction_realised_pct", "max")).to_string())
    print(f"\nlargest spread across the four laws at one point: "
          f"{float((hi - lo).max()):.2f} percentage points")
    print(f"wrote {OUT_CSV} and {OUT_TEX}")
    return d


if __name__ == "__main__":
    main()
