"""Is the band lost because the surfaces are too slow, or because the gust is too big?"""
import os
import argparse
import warnings

warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd

import compare as C
import plant as P
import band as _band
import delta_bound as DB
from writeonce import write_if_changed, frame_if_changed

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_CSV = os.path.join(HERE, "feas_test.csv")
OUT_TEX = os.path.join(HERE, "paper_AST", "feas_numbers.tex")

C.set_operating_point(55.0, 1.30)
_RATE0 = P.RATE.copy()
_SIGMA0 = P.SIGMA


def trial(seed, amp_hi):
    rng = np.random.RandomState(4_000_000 + seed)
    b = rng.normal(0, 0.12)
    model = C.BiasedModel(C.Sur, b)
    sensor = rng.uniform(0.002, 0.006)
    rate_scale = rng.uniform(0.7, 1.3)
    P.RATE = _RATE0 * rate_scale
    sigma_scale = rng.uniform(0.7, 1.4)
    P.SIGMA = _SIGMA0 * sigma_scale
    g = P.VonKarmanGust(rng, amp=rng.uniform(0.03, amp_hi))
    g.w = 2 * np.pi * np.exp(rng.uniform(np.log(0.2), np.log(1.5), len(g.w)))
    eps = _band.EPS
    try:
        L = DB.instrumented_bfasta(model, gust=g, sensor=sensor, seed=seed,
                                   eps=eps)
    finally:
        P.RATE = _RATE0.copy()
        P.SIGMA = _SIGMA0
    n = len(L["viol"])
    ss = slice(int(0.6 * n), None)
    return dict(seed=seed,
                gust_amp=float(g.A * np.sqrt(len(g.w))),
                rate_scale=float(rate_scale),
                settled_max=float(np.max(L["viol"][ss])),
                band_lost=bool(np.max(L["viol"][ss]) >= eps),
                rate_binds_pct=float(100.0 * np.mean(L["ratefrac"][ss] > 1.0)),
                rate_max=float(np.max(L["ratefrac"][ss])),
                delta=float(np.max(np.abs(L["gdd"]))))


def main(n, amp_hi):
    d = pd.DataFrame([trial(k, amp_hi) for k in range(n)])
    frame_if_changed(OUT_CSV, d, index=False)
    held, lost = d[~d.band_lost], d[d.band_lost]
    V = {
        "ftN": str(len(d)),
        "ftNLost": str(len(lost)),
        "ftAmpHi": f"{amp_hi:g}",
        "ftBindsHeld": f"{held.rate_binds_pct.mean():.1f}",
        "ftBindsLost": f"{lost.rate_binds_pct.mean():.1f}" if len(lost) else "--",
        "ftRateMaxHeld": f"{held.rate_max.max():.1f}",
        "ftRateMaxLost": f"{lost.rate_max.max():.1f}" if len(lost) else "--",
        "ftAmpHeld": f"{held.gust_amp.mean():.3f}",
        "ftAmpLost": f"{lost.gust_amp.mean():.3f}" if len(lost) else "--",
        "ftCorrBindsLoss": f"{np.corrcoef(d.rate_binds_pct, d.band_lost.astype(float))[0,1]:+.2f}",
        "ftCorrAmpLoss": f"{np.corrcoef(d.gust_amp, d.band_lost.astype(float))[0,1]:+.2f}",
        "ftCorrRateLoss": f"{np.corrcoef(d.rate_scale, d.band_lost.astype(float))[0,1]:+.2f}",
    }
    lines = ["% feas_numbers.tex -- generated by feas_test.py. Do not edit.", ""]
    lines += ["\\newcommand{\\%s}{%s}" % (k, v) for k, v in V.items()]
    write_if_changed(OUT_TEX, "\n".join(lines) + "\n")

    print(f"{len(d)} trials, gust amplitude up to {amp_hi:g}; "
          f"{len(lost)} lost the settled band\n")
    print(f"  rate limit binding, settled window:  held {V['ftBindsHeld']} % of "
          f"steps, lost {V['ftBindsLost']} %")
    print(f"  peak commanded rate / limit:         held {V['ftRateMaxHeld']}, "
          f"lost {V['ftRateMaxLost']}")
    print(f"  mean gust amplitude:                 held {V['ftAmpHeld']}, "
          f"lost {V['ftAmpLost']}")
    print(f"\n  correlation of band loss with rate binding {V['ftCorrBindsLoss']}, "
          f"with gust amplitude {V['ftCorrAmpLoss']}, "
          f"with the rate limit itself {V['ftCorrRateLoss']}")
    print(f"\nwrote {OUT_CSV} and {OUT_TEX}")
    return d


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=120)
    ap.add_argument("--amp-hi", type=float, default=0.14)
    a = ap.parse_args()
    main(a.n, a.amp_hi)
