"""What gamma actually costs, and where its ceiling is."""
import os
import argparse
import warnings

warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd

import compare as C
import plant as P
import band as _band

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "gamma_sweep.csv")
GAMMAS = [0.5, 1.0, 2.0, 3.0, 5.0, 8.0, 12.0, 20.0]

C.set_operating_point(55.0, 1.30)
_RATE0 = P.RATE.copy()
_SIGMA0 = P.SIGMA


def one(seed, gamma, eps):
    rng = np.random.RandomState(2_000_000 + seed)
    model = C.BiasedModel(C.Sur, rng.normal(0, 0.12))
    sensor = rng.uniform(0.002, 0.006)
    P.RATE = _RATE0 * rng.uniform(0.7, 1.3)
    P.SIGMA = _SIGMA0 * rng.uniform(0.7, 1.4)
    g = P.VonKarmanGust(rng, amp=rng.uniform(0.03, 0.07))
    g.w = 2 * np.pi * np.exp(rng.uniform(np.log(0.2), np.log(1.5), len(g.w)))
    try:
        L = C.run_bfasta(model, gust=g, sensor=sensor, seed=seed, eps=eps,
                         gamma=gamma)
    finally:
        P.RATE = _RATE0.copy()
        P.SIGMA = _SIGMA0
    n = len(L["t"])
    settled = slice(int(0.6 * n), None)
    return dict(seed=seed, gamma=gamma,
                whole_max=float(L["viol"].max()),
                settled_max=float(L["viol"][settled].max()),
                descent=float(C.loud_level() - L["spl"][settled].mean()))


def main(n):
    eps = _band.EPS
    d = pd.DataFrame([one(k, gm, eps) for gm in GAMMAS for k in range(n)])
    d.to_csv(OUT, index=False)
    t = d.groupby("gamma").agg(whole_max=("whole_max", "max"),
                               settled_max=("settled_max", "max"),
                               descent=("descent", "mean"),
                               inside=("whole_max", lambda v: float((v < eps).mean())))
    print(f"band eps = {eps}, {n} trials per gamma\n")
    print(t.round(4).to_string())
    ok = t.index[t.whole_max < eps]
    print(f"\n  gamma values whose whole-run maximum stays inside the band: "
          f"{list(ok) if len(ok) else 'none'}")
    print(f"  descent varies by {t.descent.max()-t.descent.min():.3f} dB across "
          f"the sweep")

    GAMMA = 3.0
    top = float(t.inside.max())
    plateau = [g for g in t.index if abs(float(t.inside[g]) - top) < 1e-9]
    V = dict(
        gsN=len(d) // len(GAMMAS),
        gsLo=f"{min(GAMMAS):g}", gsHi=f"{max(GAMMAS):g}",
        gsGamma=f"{GAMMA:g}",
        gsPlateauHi=f"{max(plateau):g}",
        gsInsidePlateau=f"{100*top:.0f}",
        gsInsideHi=f"{100*float(t.inside[max(GAMMAS)]):.0f}",
        gsDescentSpread=f"{t.descent.max()-t.descent.min():.2f}",
    )
    lines = ["% gamma_numbers.tex -- generated by gamma_sweep.py. Do not edit.",
             ""]
    lines += ["\\newcommand{\\%s}{%s}" % (k, v) for k, v in V.items()]
    from writeonce import write_if_changed
    write_if_changed(os.path.join(HERE, "paper_AST", "gamma_numbers.tex"),
                     "\n".join(lines) + "\n")
    print(f"\n  plateau of band-holding runs to gamma = {max(plateau):g} "
          f"({100*top:.0f} % of trials), falling to "
          f"{100*float(t.inside[max(GAMMAS)]):.0f} % at gamma = {max(GAMMAS):g}")
    print(f"\nwrote {OUT} and paper_AST/gamma_numbers.tex")
    return t


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=40)
    main(ap.parse_args().n)
