"""What an error in the DIRECTION of the lift Jacobian does to the constraint."""
import os
import argparse
import warnings

warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd

import compare as C
import plant as P
import band as _band
from writeonce import write_if_changed, frame_if_changed

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_CSV = os.path.join(HERE, "jacobian_direction.csv")
OUT_TEX = os.path.join(HERE, "paper_AST", "jac_numbers.tex")
ANGLES = [0.0, 1.0, 2.0, 5.0, 10.0, 20.0, 30.0, 45.0, 60.0, 75.0, 85.0]

C.set_operating_point(55.0, 1.30)
_RATE0 = P.RATE.copy()
_SIGMA0 = P.SIGMA


class RotatedJacobian:
    def __init__(self, base, theta_deg, axis=(0.0, 1.0, -1.0)):
        self._cl = self._CL(base, theta_deg, np.asarray(axis, float))
        self._spl = base._spl
        self._cm = getattr(base, "_cm", None)

    class _CL:
        def __init__(self, base, theta_deg, axis):
            self._c = base._cl
            self._t = np.radians(theta_deg)
            self._axis = axis

        def predict(self, X):
            return self._c.predict(X)

        def grad(self, x):
            g = np.asarray(self._c.grad(x), float)
            if self._t == 0.0:
                return g
            n = np.linalg.norm(g[:3])
            if n < 1e-12:
                return g
            u = g[:3] / n
            v = self._axis - (self._axis @ u) * u
            nv = np.linalg.norm(v)
            if nv < 1e-9:
                v = np.array([1.0, 0.0, 0.0]) - u[0] * u
                nv = np.linalg.norm(v)
            v /= nv
            rot = n * (np.cos(self._t) * u + np.sin(self._t) * v)
            out = np.array(g, float)
            out[:3] = rot
            return out


def one(theta, seed):
    rng = np.random.RandomState(3_000_000 + seed)
    model = RotatedJacobian(C.Sur, theta)
    sensor = rng.uniform(0.002, 0.006)
    P.RATE = _RATE0 * rng.uniform(0.7, 1.3)
    P.SIGMA = _SIGMA0 * rng.uniform(0.7, 1.4)
    g = P.VonKarmanGust(rng, amp=rng.uniform(0.03, 0.07))
    g.w = 2 * np.pi * np.exp(rng.uniform(np.log(0.2), np.log(1.5), len(g.w)))
    try:
        L = C.run_bfasta(model, gust=g, sensor=sensor, seed=seed,
                         eps=_band.EPS)
    finally:
        P.RATE = _RATE0.copy()
        P.SIGMA = _SIGMA0
    n = len(L["t"])
    ss = slice(int(0.6 * n), None)
    return dict(theta=theta, seed=seed,
                settled_max=float(np.max(L["viol"][ss])),
                settled_rms=float(np.sqrt(np.mean(L["viol"][ss] ** 2))),
                whole_max=float(np.max(L["viol"])),
                descent=float(C.loud_level() - np.mean(L["spl"][ss])))


def main(n, reuse=False):
    eps = _band.EPS
    if reuse and os.path.exists(OUT_CSV):
        d = pd.read_csv(OUT_CSV)
        print(f"reusing {OUT_CSV} ({len(d)} runs)")
    else:
        d = pd.DataFrame([one(t, k) for t in ANGLES for k in range(n)])
        frame_if_changed(OUT_CSV, d, index=False)
    t = d.groupby("theta").agg(settled_max=("settled_max", "max"),
                               settled_rms=("settled_rms", "mean"),
                               descent=("descent", "mean"))
    t["inside"] = d.groupby("theta").settled_max.apply(
        lambda v: float((v < eps).mean()))
    print(f"band eps = {eps}, {n} trials per angle\n")
    print(t.round(4).to_string())

    held = []
    for a in sorted(ANGLES):
        if float(t.settled_max[a]) < eps:
            held.append(a)
        else:
            break
    V = {
        "jdN": str(n),
        "jdAngles": f"{min(ANGLES):g}" + r"\text{--}" + f"{max(ANGLES):g}",
        "jdHeldTo": f"{max(held):g}" if held else "0",
        "jdMaxAtHeld": f"{float(t.settled_max[max(held)]):.3f}" if held else "--",
        "jdMaxAtWorst": f"{float(t.settled_max[max(ANGLES)]):.3f}",
        "jdRmsAtZero": f"{float(t.settled_rms[0.0]):.4f}",
        "jdRmsAtWorst": f"{float(t.settled_rms[max(ANGLES)]):.4f}",
        "jdDescentDrop": f"{float(t.descent[0.0] - t.descent[max(ANGLES)]):.2f}",
        "jdGainAtHeld": (f"{1/np.cos(np.radians(max(held))):.2f}" if held else "--"),
    }
    a = np.linspace(0, 12, 13)
    dd = np.linspace(-10, 10, 7)
    norms = [float(np.linalg.norm(
                np.asarray(C.Sur._cl.grad([A, d1, d2, U]), float)[:3]))
             for A in a for d1 in dd for d2 in dd for U in (45.0, 55.0, 70.0)]
    V["jdJmin"] = f"{min(norms):.3f}"
    V["jdJmax"] = f"{max(norms):.3f}"
    V["jdJgrid"] = f"{len(norms)}"

    lines = ["% jac_numbers.tex -- generated by jacobian_direction.py. Do not edit.",
             ""]
    lines += ["\\newcommand{\\%s}{%s}" % (k, v) for k, v in V.items()]
    write_if_changed(OUT_TEX, "\n".join(lines) + "\n")
    print(f"\n  band held to theta = {V['jdHeldTo']} deg; "
          f"settled max there {V['jdMaxAtHeld']}, "
          f"at {max(ANGLES):g} deg {V['jdMaxAtWorst']}")
    print(f"wrote {OUT_CSV} and {OUT_TEX}")
    return t


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=5)
    ap.add_argument("--reuse", action="store_true")
    a = ap.parse_args()
    main(a.n, a.reuse)
