#!/usr/bin/env python3
"""Generate the wing-section schematic as standalone TikZ."""
from __future__ import annotations
import os, sys, warnings
warnings.filterwarnings("ignore")
import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "rans"))
from geometry import raw_coordinates, HINGE1, HINGE2   # noqa: E402

S = 10.5
ALPHA = 8.0
D1, D2 = 10.0, 8.0


def rot(c, deg, about=(0.0, 0.0)):
    a = np.radians(-deg)
    R = np.array([[np.cos(a), -np.sin(a)], [np.sin(a), np.cos(a)]])
    return (np.asarray(c, float) - about) @ R.T + about


def pth(c, thin=5, scale=S, off=(0.0, 0.0)):
    c = np.asarray(c, float)
    c = np.vstack([c[::thin], c[-1]])
    return " -- ".join(f"({scale*x+off[0]:.4f},{scale*y+off[1]:.4f})" for x, y in c)


def build(out="paper_AST/section_schematic.tex"):
    neutral = rot(raw_coordinates(0.0, 0.0), ALPHA)
    seg1 = rot(raw_coordinates(D1, 0.0), ALPHA)
    defl = rot(raw_coordinates(D1, D2), ALPHA)

    h1 = rot(np.array([[HINGE1, 0.0]]), ALPHA)[0]
    i2 = np.argmin(np.abs(seg1[:, 0] - rot(np.array([[HINGE2, 0.0]]), ALPHA)[0][0]))
    h2 = seg1[i2]
    te_n = rot(np.array([[1.0, 0.0]]), ALPHA)[0]
    te_d = defl[0]

    ZM, ZR = 3.0, 0.050
    ins = np.array([12.15, 3.55])
    zoom = lambda c: (np.asarray(c, float) - h1) * ZM

    def runs(coords):
        m = np.linalg.norm(coords - h1, axis=1) < ZR
        idx = np.where(m)[0]
        out, start = [], 0
        for k in range(1, len(idx) + 1):
            if k == len(idx) or idx[k] != idx[k - 1] + 1:
                seg = coords[idx[start:k]]
                if len(seg) > 2:
                    out.append(seg)
                start = k
        return out

    ins_defl = "\n".join(
        r"  \draw[ink,line width=0.9pt] " + pth(zoom(r), thin=1, scale=S) + ";"
        for r in runs(defl))
    ins_neut = "\n".join(
        r"  \draw[faint,line width=0.4pt,densely dotted] " + pth(zoom(r), thin=1, scale=S) + ";"
        for r in runs(neutral))

    A = np.degrees(np.arctan2(te_n[1], te_n[0]))

    tex = rf"""% generated by make_schematic.py -- do not edit by hand
\documentclass[border=4pt]{{standalone}}
\usepackage{{tikz}}
\usepackage{{amsmath}}
\usetikzlibrary{{arrows.meta,angles,quotes,calc,patterns,backgrounds}}
\begin{{document}}
\begin{{tikzpicture}}[
  >={{Stealth[length=2.1mm]}},
  ink/.style={{black!88}},
  faint/.style={{black!32}},
  dim/.style={{black!55,line width=0.35pt}},
  lab/.style={{font=\small,black!88}},
  slab/.style={{font=\scriptsize,black!72}},
  note/.style={{font=\scriptsize,black!85,align=left,inner sep=2pt}},
  hd/.style={{font=\scriptsize\bfseries,black!88}},
]

%% ---------------------------------------------------------- freestream
\foreach \y in {{-1.5,-0.7,0.1,0.9,1.7}} {{
  \draw[->,faint,line width=0.5pt] (-3.5,\y) -- (-2.25,\y);
}}
\node[lab] at (-2.85,2.35) {{$U_\infty$}};

%% ---------------------------------------------------------- reference axes
\coordinate (LE) at (0,0);
\coordinate (HX) at (4.3,0);
\coordinate (TEN) at ({S*te_n[0]:.3f},{S*te_n[1]:.3f});
\draw[dim,densely dashed] (-2.0,0) -- (HX);
\pic[draw=black!62,angle radius=3.15cm,line width=0.4pt,
     "{{\small$\alpha$}}",angle eccentricity=1.11] {{angle=TEN--LE--HX}};

%% ---------------------------------------------------------- neutral outline
\draw[faint,line width=0.45pt,densely dotted] {pth(neutral)} -- cycle;
\draw[dim,densely dashed] (LE) -- (TEN);

%% ---------------------------------------------------------- deflected section
\begin{{scope}}[on background layer]
  \fill[black!8] {pth(defl)} -- cycle;
\end{{scope}}
\draw[ink,line width=0.9pt] {pth(defl)} -- cycle;

%% ---------------------------------------------------------- hinges
\filldraw[fill=white,draw=black!85,line width=0.7pt]
  ({S*h1[0]:.3f},{S*h1[1]:.3f}) circle (1.7pt);
\filldraw[fill=white,draw=black!85,line width=0.7pt]
  ({S*h2[0]:.3f},{S*h2[1]:.3f}) circle (1.7pt);
\draw[dim] ({S*h1[0]:.3f},{S*h1[1]:.3f}) -- ++(0,1.55);
\draw[dim] ({S*h2[0]:.3f},{S*h2[1]:.3f}) -- ++(0,2.25);
\node[slab,align=center] at ({S*h1[0]:.3f},{S*h1[1]+1.55:.3f})
  [above] {{Hinge 1\\ $x/c={HINGE1:.2f}$}};
\node[slab,align=center] at ({S*h2[0]:.3f},{S*h2[1]+2.25:.3f})
  [above] {{Hinge 2\\ $x/c={HINGE2:.2f}$}};

%% ---------------------------------------------------------- deflections
\coordinate (H1) at ({S*h1[0]:.3f},{S*h1[1]:.3f});
\coordinate (H2) at ({S*h2[0]:.3f},{S*h2[1]:.3f});
\coordinate (H1REF) at ($(H1)+({A:.3f}:2.9)$);
\coordinate (H1SEG) at ($(H2)$);
\draw[dim,densely dashed] (H1) -- (H1REF);
\draw[->,black!80,line width=0.65pt] (H1) -- (H2);
\pic[draw=black!70,angle radius=3.05cm,line width=0.38pt,
     "{{\scriptsize$\delta_1$}}",angle eccentricity=1.13] {{angle=H2--H1--H1REF}};

\coordinate (H2REF) at ($(H2)+({A-D1:.3f}:2.0)$);
\coordinate (TED) at ({S*te_d[0]:.3f},{S*te_d[1]:.3f});
\draw[dim,densely dashed] (H2) -- (H2REF);
\draw[->,black!80,line width=0.65pt] (H2) -- (TED);
\pic[draw=black!70,angle radius=1.75cm,line width=0.38pt,
     "{{\scriptsize$\delta_2$}}",angle eccentricity=1.22] {{angle=TED--H2--H2REF}};

%% ---------------------------------------------------------- observer
\coordinate (OBS) at ($(TED)+(41:2.85)$);
\coordinate (TEX) at ($(TED)+(1.75,0)$);
\draw[->,ink,line width=0.6pt] (TED) -- (OBS);
\node[lab] at ($(TED)+(41:1.55)$) [above left=-2pt] {{$r_e$}};
\draw[dim,densely dashed] (TED) -- (TEX);
\pic[draw=black!58,angle radius=1.15cm,line width=0.34pt,
     "{{\scriptsize$\theta_e$}}",angle eccentricity=1.40] {{angle=TEX--TED--OBS}};
\node[slab,align=left,anchor=south west] at ($(TED)+(41:2.95)$)
  {{Observer\\ $(r_e,\theta_e,\phi_e)$}};

%% ---------------------------------------------------------- BL callout
\node[slab,anchor=north west] at ($(TED)+(0.15,-0.95)$)
   {{$\delta^*_s,\ \delta^*_p$}};
\draw[dim] ($(TED)+(0.17,-0.92)$) -- ($(TED)+(-0.06,-0.08)$);

%% ---------------------------------------------------------- chord dimension
\draw[dim,|<->|] (0,-3.05) -- ({S:.3f},-3.05)
  node[slab,midway,below] {{Chord $c=1$\,m}};

%% ---------------------------------------------------------- inset
\begin{{scope}}[shift={{({ins[0]:.2f},{ins[1]:.2f})}}]
  \draw[black!25,line width=0.4pt] (0,0) circle ({S*ZR*ZM:.3f});
{ins_neut}
{ins_defl}
  \filldraw[fill=white,draw=black!85,line width=0.7pt] (0,0) circle (1.7pt);
  \node[slab,align=center,anchor=south] at (0,{S*ZR*ZM+0.12:.2f})
     {{Hinge detail, $\times{ZM:g}$}};
  \node[slab,anchor=north,align=center] at (0,{-(S*ZR*ZM+0.12):.2f})
     {{Sealed kink: no step,\\ no gap, no side edge}};
\end{{scope}}
\draw[black!35,line width=0.4pt] (H1) circle ({S*ZR:.3f});
\draw[dim,densely dotted] ($(H1)+({S*ZR*0.7:.2f},{S*ZR*0.7:.2f})$)
   -- ({ins[0]-S*ZR*ZM*0.72:.2f},{ins[1]-S*ZR*ZM*0.72:.2f});

%% ---------------------------------------------------------- note panels
\node[note,anchor=north west] at (-3.6,-3.95)
 {{\textbf{{Controls}}\\[1.5pt]
   $\boldsymbol{{\delta}}=[\alpha,\ \delta_1,\ \delta_2]^\top$\\[1.5pt]
   $\alpha\in[0,12]^\circ$\\
   $\delta_1,\delta_2\in[-10,10]^\circ$}};

\node[note,anchor=north west,text width=6.1cm] at (2.4,-3.95)
 {{\textbf{{Sign convention}}\\[1.5pt]
   $\alpha>0$ nose up; $\delta_i>0$ trailing edge down.
   $\delta_2$ is measured \emph{{relative to segment~1}}, so the two
   deflections compound.}};

\node[note,anchor=north west] at (9.9,-3.95)
 {{\textbf{{Outputs}}\\[1.5pt]
   $C_L$;\ \ $C_M$ about $c/4$\\
   $\delta^*_s,\ \delta^*_p$ at the trailing edge\\
   $\mathrm{{SPL}}(f)$, overall and A-weighted}};

\end{{tikzpicture}}
\end{{document}}
"""
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w").write(tex)
    print(f"wrote {out}")
    return out


if __name__ == "__main__":
    build()
