"""The rate-limit sweep, as macros."""
import os
import warnings

warnings.filterwarnings("ignore")
import pandas as pd

from writeonce import write_if_changed

HERE = os.path.dirname(os.path.abspath(__file__))
CSV = os.path.join(HERE, "rate_limit_sweep.csv")
OUT = os.path.join(HERE, "paper_AST", "rate_numbers.tex")

LABEL = {"SG-FTSMC": "Ft", "BF-STA": "Bf", "CLF-QP": "Qp", "MPC": "Mp"}


def main():
    d = pd.read_csv(CSV)
    per = d.groupby("controller").lift_RMS
    mean, lo, hi = per.mean(), per.min(), per.max()

    V = {
        "rlFactor": f"{d.rate_scale.max()/d.rate_scale.min():.0f}",
        "rlLo": f"{d.rate_scale.min():g}", "rlHi": f"{d.rate_scale.max():g}",
        "rlAcross": f"{mean.max() - mean.min():.4f}",
        "rlWithin": f"{float((hi - lo).max()):.4f}",
        "rlRatio": f"{(mean.max()-mean.min())/max(float((hi-lo).max()), 1e-12):.0f}",
    }
    for name, tag in LABEL.items():
        if name in mean.index:
            V["rlRms" + tag] = f"{mean[name]:.3f}"

    lines = ["% rate_numbers.tex -- generated by rate_numbers.py. Do not edit.", ""]
    lines += ["\\newcommand{\\%s}{%s}" % (k, v) for k, v in V.items()]
    write_if_changed(OUT, "\n".join(lines) + "\n")

    print(d.pivot_table(index="rate_scale", columns="controller",
                        values="lift_RMS").round(5).to_string())
    print(f"\n  spread between laws            {V['rlAcross']}")
    print(f"  spread within a law, whole sweep {V['rlWithin']}")
    print(f"  ratio                            {V['rlRatio']}")
    print(f"\nwrote {OUT}")


if __name__ == "__main__":
    main()
