/* gp_model.h -- interface to the exported Gaussian-process model.
 * Generated by export_model.py; do not edit by hand.
 */
#ifndef GP_MODEL_H
#define GP_MODEL_H

#define GP_N        375
#define GP_D        4
#define GP_NTRI     70500
#define SP_NU       41
#define SP_NCL      81

#define CTRL_A_LO   0.000000f
#define CTRL_A_HI   12.000000f
#define CTRL_D_LIM  10.000000f

extern const float gp_in_mu[GP_D];
extern const float gp_in_sd[GP_D];
extern const float gp_xn[GP_N * GP_D];

extern const float gp_cl_inv_ls2[GP_D];
extern const float gp_cl_alpha[GP_N];
extern const float gp_cl_ym, gp_cl_ys;

extern const float gp_spl_inv_ls2[GP_D];
extern const float gp_spl_alpha[GP_N];
extern const float gp_spl_ym, gp_spl_ys;
extern const float gp_spl_chol[GP_NTRI];

extern const float sp_u_grid[SP_NU];
extern const float sp_cl_grid[SP_NCL];
extern const float sp_table[SP_NU * SP_NCL * 3];
extern const float sp_gate[SP_NU * SP_NCL];

#endif
