#!/usr/bin/env python3
"""Turn the measured deployment results into LaTeX macros."""
from __future__ import annotations
import os, sys, json, subprocess, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "paper_AST", "pil_numbers.tex")

FLASH_TOTAL = 2 * 1024 * 1024
RAM_TOTAL = 512 * 1024
def _dt_firmware():
    for line in open(os.path.join(HERE, "ctrl.h")):
        if line.strip().startswith("#define CTRL_DT"):
            return float(line.split()[2].rstrip("f"))
    raise RuntimeError("CTRL_DT not found in ctrl.h")


def _dt_study():
    import re as _re
    src = open(os.path.join(ROOT, "compare.py")).read()
    m = _re.search(r"def run_sgftsmc\([^)]*?dt=([0-9.]+)", src, _re.S)
    return float(m.group(1)) if m else None


DT = _dt_firmware()
DT_STUDY = _dt_study()
def fidelity_reference(res):
    return res.get("closed_loop", {}).get("settled_lift_band")

ARMFLAGS = ("-mcpu=cortex-m7 -mthumb -mfpu=fpv5-d16 -mfloat-abi=hard "
            "-O2 -ffunction-sections -fdata-sections").split()


def footprint():
    objs = []
    for src in ("ctrl.c", "gp_model.c", "pil_core.c"):
        o = f"/tmp/pil_{src[:-2]}.o"
        subprocess.run(["arm-none-eabi-gcc", *ARMFLAGS, "-c",
                        os.path.join(HERE, src), "-o", o], check=True)
        objs.append(o)
    out = subprocess.run(["arm-none-eabi-size", "-t", "-d", *objs],
                         capture_output=True, text=True, check=True).stdout
    tot = out.strip().splitlines()[-1].split()
    text, data, bss = int(tot[0]), int(tot[1]), int(tot[2])

    sec = subprocess.run(["arm-none-eabi-size", "-A", "-d", objs[1]],
                         capture_output=True, text=True, check=True).stdout
    chol = 0
    for line in sec.splitlines():
        m = re.match(r"\s*\.rodata\.gp_spl_chol\s+(\d+)", line)
        if m:
            chol = int(m.group(1))
    return dict(flash=text + data, ram=bss + data, chol=chol)


def sci(v, sig=1):
    if v == 0:
        return "0"
    e = 0
    while abs(v) < 1.0:
        v *= 10.0; e -= 1
    while abs(v) >= 10.0:
        v /= 10.0; e += 1
    return f"{v:.{sig}f}\\times 10^{{{e}}}"


def main():
    res_path = os.path.join(HERE, "pil_results.json")
    res = json.load(open(res_path)) if os.path.exists(res_path) else {}
    sim_path = os.path.join(HERE, "pil_sim_results.json")
    sim = json.load(open(sim_path)) if os.path.exists(sim_path) else {}
    TRAJ_TOL = 1e-2
    dtraj = res.get("closed_loop", {}).get("max_trajectory_deviation_deg")
    board_current = dtraj is not None and dtraj < TRAJ_TOL

    stale_table = False
    exp_early = json.load(open(os.path.join(HERE, "export_summary.json"))) \
        if os.path.exists(os.path.join(HERE, "export_summary.json")) else {}
    tgt_early = res.get("target", {})
    if exp_early and tgt_early:
        want = (exp_early.get("nu"), exp_early.get("ncl"))
        got = (tgt_early.get("sp_nu"), tgt_early.get("sp_ncl"))
        if None not in want and None not in got and want != got:
            print(f"  board carries a {got[0]}x{got[1]} set-point table; the "
                  f"exporter last wrote {want[0]}x{want[1]}. The firmware is "
                  f"behind the model -- reflash and re-run before submission.")
            board_current = False
            stale_table = True

    if board_current:
        print(f"  board run agrees with the current model to {dtraj:.2e} deg; "
              f"every quantity below is measured on the target")
    elif sim:
        for k in ("fidelity", "closed_loop", "monte_carlo", "faults"):
            if k in sim:
                res[k] = sim[k]
        why = ("no closed loop in the board run" if dtraj is None else
               "board carries a superseded set-point table" if stale_table else
               f"board diverges from the current model by {dtraj:.2e} deg")
        print(f"  {why}: fidelity, closed loop and faults taken from the host "
              f"build (pil_sim_results.json); timing and footprint from the board")
        print("  -> a board run on the rebuilt model is still owed before "
              "submission")
    else:
        print("  WARNING: board run looks stale and there is no host build to "
              "fall back on")
    alt_path = os.path.join(HERE, "pil_results_nocache.json")
    alt = json.load(open(alt_path)) if os.path.exists(alt_path) else {}
    exp_path = os.path.join(HERE, "export_summary.json")
    exp = json.load(open(exp_path)) if os.path.exists(exp_path) else {}
    fp = footprint()
    L = []
    add = lambda k, v: L.append(f"\\newcommand{{\\{k}}}{{{v}}}")

    L.append("% pil_numbers.tex -- generated by pil/make_tex.py; do not edit.")
    L.append("\\providecommand{\\pilTBD}{\\textbf{[board run pending]}}")

    tgt = res.get("target", {})
    add("pilN", tgt.get("gp_n", 375))
    add("pilMapU", exp.get("nu", tgt.get("sp_nu", 25)))
    add("pilMapCL", exp.get("ncl", tgt.get("sp_ncl", 41)))
    if exp:
        add("pilTableDb", f"{exp['table_dspl_mean']:+.3f}")
        add("pilTableDbMax", f"{exp['table_dspl_max']:+.2f}")
    else:
        add("pilTableDb", "\\pilTBD"); add("pilTableDbMax", "\\pilTBD")

    add("pilFlashKB", f"{fp['flash']/1024:.0f}")
    add("pilFlashPct", f"{100*fp['flash']/FLASH_TOTAL:.1f}")
    add("pilRamB", f"{fp['ram']}")
    add("pilRamPct", f"{100*fp['ram']/RAM_TOTAL:.2f}")
    add("pilCholKB", f"{fp['chol']/1024:.0f}")
    add("pilFlashNoGateKB", f"{(fp['flash']-fp['chol'])/1024:.0f}")

    b = res.get("bench", {})
    clk = b.get("clk", 0)
    if clk:
        us = lambda c: 1e6 * c / clk
        pct = lambda c: 100.0 * c / clk / DT
        add("pilClk", f"{clk/1e6:.0f}")
        add("pilInnerUs", f"{us(b['inner'][1]):.0f}")
        add("pilInnerPct", f"{pct(b['inner'][1]):.1f}")
        add("pilDtMs", f"{1e3*DT:.0f}")
        add("pilHz", f"{1/DT:.0f}")
        if DT_STUDY:
            add("pilDtStudyMs", f"{1e3*DT_STUDY:.0f}")
            add("pilHzStudy", f"{1/DT_STUDY:.0f}")
            add("pilInnerPctStudy",
                f"{100.0*b['inner'][1]/clk/DT_STUDY:.1f}")
        add("pilInnerMaxUs", f"{us(b['inner'][2]):.0f}")
        add("pilOuterUs", f"{us(b['outer'][1]):.0f}")
        add("pilOuterPct", f"{pct(b['outer'][1]):.1f}")
        add("pilGpUs", f"{us(b['gp'][1]):.0f}")
        add("pilSigmaUs", f"{us(b['sigma'][1]):.0f}")
        add("pilMapUs", f"{us(b['map_mean']):.1f}")
        add("pilCache", ("both caches enabled" if b.get("cache", 0) == 3 else
                         "caches disabled" if b.get("cache", 0) == 0 else
                         "one cache enabled"))
        tg = res.get("target", {})
        add("pilOpt", tg.get("optimisation", "\\pilTBD"))
        add("pilGcc", tg.get("gcc_major", "\\pilTBD"))
        ab = alt.get("bench", {})
        if ab.get("clk"):
            au = lambda c: 1e6 * c / ab["clk"]
            ap = lambda c: 100.0 * c / ab["clk"] / DT
            add("pilNcInnerUs", f"{au(ab['inner'][1]):.0f}")
            add("pilNcInnerPct", f"{ap(ab['inner'][1]):.1f}")
            add("pilNcOuterUs", f"{au(ab['outer'][1]):.0f}")
            add("pilNcOuterPct", f"{ap(ab['outer'][1]):.1f}")
            add("pilNcGpUs", f"{au(ab['gp'][1]):.0f}")
            add("pilNcSigmaUs", f"{au(ab['sigma'][1]):.0f}")
            add("pilSpeedInner", f"{ab['inner'][1]/b['inner'][1]:.1f}")
            add("pilSpeedGate", f"{ab['sigma'][1]/b['sigma'][1]:.1f}")
        else:
            for k in ("pilNcInnerUs", "pilNcInnerPct", "pilNcOuterUs",
                      "pilNcOuterPct", "pilNcGpUs", "pilNcSigmaUs",
                      "pilSpeedInner", "pilSpeedGate"):
                add(k, "\\pilTBD")
    else:
        for k in ("pilClk", "pilInnerUs", "pilInnerPct", "pilInnerMaxUs",
                  "pilOuterUs", "pilOuterPct", "pilGpUs", "pilSigmaUs",
                  "pilMapUs", "pilCache", "pilOpt", "pilGcc",
                  "pilNcInnerUs", "pilNcInnerPct", "pilNcOuterUs",
                  "pilNcOuterPct", "pilNcGpUs", "pilNcSigmaUs",
                  "pilSpeedInner", "pilSpeedGate"):
            add(k, "\\pilTBD")

    f = res.get("fidelity", {})
    if f:
        s0, s1 = f["scenario0"], f["scenario1"]
        worst_du = max(s0["max_du_deg"], s1["max_du_deg"])
        worst_ds = max(s0["max_ds"], s1["max_ds"])
        add("pilFidDu", sci(worst_du))
        add("pilFidDuPlain", sci(worst_du))
        add("pilFidS", sci(worst_ds))
        fid_ref = fidelity_reference(res)
        if fid_ref:
            add("pilFidRef", f"{fid_ref:.4f}")
            add("pilFidSPct", f"{100*worst_ds/fid_ref:.0f}")
        else:
            add("pilFidRef", "\\pilTBD"); add("pilFidSPct", "\\pilTBD")
    else:
        for k in ("pilFidDu", "pilFidDuPlain", "pilFidS", "pilFidSPct",
                  "pilFidRef"):
            add(k, "\\pilTBD")

    c = res.get("closed_loop", {})
    if c:
        add("pilLoud", f"{c['loud_level']:.2f}")
        add("pilDescent", f"{c['descent_dB']:.2f}")
        add("pilBand", f"{c['settled_lift_band']:.3f}")
        add("pilTwinDev", sci(c["max_trajectory_deviation_deg"]))
    else:
        for k in ("pilLoud", "pilDescent", "pilBand", "pilTwinDev"):
            add(k, "\\pilTBD")

    m = res.get("monte_carlo", {})
    if m:
        add("pilMcN", m["n"])
        add("pilMcDescent", f"{m['descent_mean']:.2f}")
        add("pilMcDescentLo", f"{m['descent_min']:.2f}")
        add("pilMcDescentHi", f"{m['descent_max']:.2f}")
        add("pilMcBandMax", f"{m['band_max']:.3f}")
        add("pilMcInside", m["inside_band"])
    else:
        for k in ("pilMcN", "pilMcDescent", "pilMcDescentLo", "pilMcDescentHi",
                  "pilMcBandMax", "pilMcInside"):
            add(k, "\\pilTBD")

    open(OUT, "w").write("\n".join(L) + "\n")
    print(f"wrote {os.path.relpath(OUT, ROOT)}  ({len(L)-2} macros)")
    print(f"  deployed flash {fp['flash']/1024:.0f} kB "
          f"({100*fp['flash']/FLASH_TOTAL:.1f} % of 2 MB), "
          f"RAM {fp['ram']} B ({100*fp['ram']/RAM_TOTAL:.2f} % of 512 kB)")
    if not clk:
        print("  timing macros left as \\pilTBD until a board run")


if __name__ == "__main__":
    main()
