#!/usr/bin/env python3
"""The section geometry used by the Reynolds-averaged rung."""
from __future__ import annotations
import os, warnings
warnings.filterwarnings("ignore")
import numpy as np

CHORD = 1.0
HINGE1, HINGE2 = 0.70, 0.85
NACA = "0012"
NU = 1.5e-5


def raw_coordinates(d1: float, d2: float) -> np.ndarray:
    import aerosandbox as asb
    af = asb.Airfoil(f"naca{NACA}")
    af = af.add_control_surface(deflection=d1, hinge_point_x=HINGE1)
    af = af.add_control_surface(deflection=d2, hinge_point_x=HINGE2)
    return np.asarray(af.coordinates, float)


def _self_intersects(c: np.ndarray) -> bool:
    def cross(o, a, b):
        return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0])
    n = len(c)
    step = max(1, n // 200)
    idx = list(range(0, n - 1, step))
    for ii, i in enumerate(idx):
        p1, p2 = c[i], c[i + 1]
        for j in idx[ii + 2:]:
            p3, p4 = c[j], c[j + 1]
            d1 = cross(p3, p4, p1); d2 = cross(p3, p4, p2)
            d3 = cross(p1, p2, p3); d4 = cross(p1, p2, p4)
            if ((d1 > 0) != (d2 > 0)) and ((d3 > 0) != (d4 > 0)):
                return True
    return False


FILLET_MODE = "station"

_C0 = None


def _undeflected() -> np.ndarray:
    global _C0
    if _C0 is None:
        _C0 = raw_coordinates(0.0, 0.0)
    return _C0


def _hinge_indices(x_hinge: float) -> list:
    c0 = _undeflected()
    ile = int(np.argmin(c0[:, 0]))
    out = []
    for seg in (np.arange(0, ile), np.arange(ile, len(c0))):
        if len(seg):
            out.append(int(seg[np.argmin(np.abs(c0[seg, 0] - x_hinge))]))
    return out


def _fillet(c: np.ndarray, x_hinge: float, radius: float,
            mode: str | None = None) -> np.ndarray:
    if radius <= 0:
        return c
    mode = mode or FILLET_MODE
    out = c.copy()

    if mode == "station":
        for _ in range(3):
            near = np.abs(out[:, 0] - x_hinge) < radius
            near[0] = near[-1] = False
            idx = np.where(near)[0]
            if len(idx) < 3:
                break
            sm = out.copy()
            sm[idx] = 0.25 * out[idx - 1] + 0.5 * out[idx] + 0.25 * out[idx + 1]
            out = sm
        return out

    if mode != "material":
        raise ValueError(f"unknown fillet mode {mode!r}")

    for i0 in _hinge_indices(x_hinge):
        for _ in range(3):
            seg = np.linalg.norm(np.diff(out, axis=0), axis=1)
            s = np.r_[0.0, np.cumsum(seg)]
            near = np.abs(s - s[i0]) < radius
            near[0] = near[-1] = False
            idx = np.where(near)[0]
            if len(idx) < 3:
                break
            sm = out.copy()
            sm[idx] = 0.25 * out[idx - 1] + 0.5 * out[idx] + 0.25 * out[idx + 1]
            out = sm
    return out


def section(d1: float, d2: float, fillet_radius: float = 0.012,
            close_te: bool = True) -> dict:
    c = raw_coordinates(d1, d2)
    rec = dict(d1=d1, d2=d2, n_raw=len(c),
               te_thickness=float(np.linalg.norm(c[0] - c[-1])),
               self_intersect_raw=bool(_self_intersects(c)),
               fillet_radius=fillet_radius)
    for xh in (HINGE1, HINGE2):
        c = _fillet(c, xh, fillet_radius)
    if close_te:
        te = 0.5 * (c[0] + c[-1])
        c = np.vstack([te, c[1:-1], te])
    rec["self_intersect_final"] = bool(_self_intersects(c))
    rec["chord_extent"] = float(c[:, 0].max() - c[:, 0].min())
    return dict(coords=c, **rec)


def first_cell_height(U: float, chord: float = CHORD, yplus: float = 1.0,
                      nu: float = NU) -> float:
    Rex = U * chord / nu
    cf = 0.026 / Rex ** (1 / 7)
    tau_w = 0.5 * cf * U ** 2
    u_tau = np.sqrt(tau_w)
    return yplus * nu / u_tau


def write_geo(sec: dict, path: str, U: float, farfield: float = 60.0,
              n_bl: int = 40, bl_growth: float = 1.15,
              le_size: float = 2e-3, te_size: float = 8e-4,
              mid_size: float = 4e-3, ff_size: float = 8.0,
              span_thickness: float = 0.05) -> dict:
    c = sec["coords"]
    keep = np.r_[True, np.linalg.norm(np.diff(c, axis=0), axis=1) > 1e-9]
    c = c[keep]
    if np.allclose(c[0], c[-1]):
        c = c[:-1]

    y1 = first_cell_height(U)
    bl_thickness = y1 * (bl_growth ** n_bl - 1) / (bl_growth - 1)

    lines = ["// generated by rans/geometry.py",
             f"// deflections d1={sec['d1']} d2={sec['d2']}, U={U} m/s",
             f"// first cell {y1:.3e} m (y+~1), BL field thickness {bl_thickness:.3e} m",
             "SetFactory(\"OpenCASCADE\");", ""]

    x = c[:, 0]
    s = np.where(x < 0.02, le_size, np.where(x > 0.95, te_size, mid_size))
    for i, ((xi, yi), si) in enumerate(zip(c, s), start=1):
        lines.append(f"Point({i}) = {{{xi:.9f}, {yi:.9f}, 0, {si:.6f}}};")
    n = len(c)
    lines.append(f"Spline(1) = {{{','.join(str(i) for i in range(1, n + 1))},1}};")
    lines.append("Curve Loop(1) = {1};")

    R = farfield
    lines += [f"Point(1000) = {{0.5, 0, 0, {ff_size}}};",
              f"Point(1001) = {{{0.5-R}, 0, 0, {ff_size}}};",
              f"Point(1002) = {{0.5, {R}, 0, {ff_size}}};",
              f"Point(1003) = {{{0.5+R}, 0, 0, {ff_size}}};",
              f"Point(1004) = {{0.5, {-R}, 0, {ff_size}}};",
              "Circle(101) = {1001, 1000, 1002};",
              "Circle(102) = {1002, 1000, 1003};",
              "Circle(103) = {1003, 1000, 1004};",
              "Circle(104) = {1004, 1000, 1001};",
              "Curve Loop(2) = {101,102,103,104};",
              "Plane Surface(1) = {2,1};", ""]

    lines += ["Field[1] = BoundaryLayer;",
              "Field[1].CurvesList = {1};",
              f"Field[1].Size = {y1:.6e};",
              f"Field[1].Ratio = {bl_growth};",
              f"Field[1].Thickness = {bl_thickness:.6e};",
              f"Field[1].SizeFar = {mid_size};",
              "Field[1].Quads = 1;",
              "BoundaryLayer Field = 1;", ""]

    lines += ["Mesh.Algorithm = 6;",
              "Mesh.RecombineAll = 1;",
              "Mesh.RecombinationAlgorithm = 1;",
              "Mesh 2;",
              f"Extrude {{0,0,{span_thickness}}} {{ Surface{{1}}; Layers{{1}}; Recombine; }}",
              "Mesh 3;",
              "Physical Surface(\"airfoil\") = {};   // filled by tag pass",
              ""]

    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(lines))
    return dict(path=path, n_points=n, y1=y1, bl_thickness=bl_thickness)


if __name__ == "__main__":
    import json
    for d1, d2 in [(0, 0), (10, 10), (-10, -10), (10, -10)]:
        s = section(d1, d2)
        print(json.dumps({k: v for k, v in s.items() if k != "coords"}, indent=None))
